services:
  mysql:
    container_name: 'proteus-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=proteusdb'
      - 'MYSQL_PASSWORD=proteus123'
      - 'MYSQL_ROOT_PASSWORD=proteus123'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'

  rabbitmq:
    container_name: 'proteus-rabbitmq'
    image: rabbitmq:3.13-management
    ports:
      - '15672:15672'
      - '5672:5672'